// lib/core/seed/indian_food_seed_data.dart
// Seed data for Indian regional cuisines

import 'dart:convert';

/// Indian food seed data with comprehensive regional coverage
class IndianFoodSeedData {
  /// Get all seed food items as JSON
  static List<Map<String, dynamic>> getAllFoods() {
    return [
      // ============ NORTH INDIAN ============
      // Punjabi
      _createFood(
        'punjabi_sarson_da_saag',
        'सरसों का साग',
        'Sarson Da Saag',
        'Punjab',
        146,
        5.8,
        6.8,
        11.4,
        2.4,
        0,
        0.5,
        3.3,
        162,
      ),
      _createFood(
        'punjabi_makki_di_roti',
        'मक्की की रोटी',
        'Makki Di Roti',
        'Punjab',
        228,
        4.8,
        48.2,
        1.8,
        2.1,
        0,
        0.3,
        2.1,
        35,
      ),
      _createFood(
        'punjabi_dal_makhani',
        'दाल मखनी',
        'Dal Makhani',
        'Punjab',
        117,
        5.8,
        8.1,
        6.3,
        3.2,
        0,
        0.1,
        1.9,
        36,
      ),
      _createFood(
        'punjabi_paneer_tikka',
        'पनीर टिक्का',
        'Paneer Tikka',
        'Punjab',
        238,
        14.5,
        6.2,
        18.3,
        1.2,
        0,
        0.4,
        1.1,
        207,
      ),
      _createFood(
        'punjabi_chole_bhature',
        'छोले भटूरे',
        'Chole Bhature',
        'Punjab',
        268,
        9.8,
        45.2,
        7.4,
        3.5,
        0,
        0.3,
        4.2,
        56,
      ),
      _createFood(
        'punjabi_lassi',
        'लस्सी',
        'Lassi',
        'Punjab',
        63,
        2.5,
        8.5,
        1.8,
        0,
        0,
        0.1,
        0,
        110,
      ),
      _createFood(
        'punjabi_amritsari_kulcha',
        'अमृतसरी कुल्चा',
        'Amritsari Kulcha',
        'Punjab',
        260,
        7.2,
        48.5,
        4.8,
        1.4,
        0,
        0.2,
        1.8,
        42,
      ),
      _createFood(
        'punjabi_achari_paneer',
        'अचारी पनीर',
        'Achari Paneer',
        'Punjab',
        212,
        12.8,
        5.4,
        16.5,
        0.8,
        0,
        0.3,
        1.4,
        185,
      ),

      // Kashmiri
      _createFood(
        'kashmiri_rogan_josh',
        'रोगन जोश',
        'Rogan Josh',
        'Kashmir',
        198,
        15.2,
        4.8,
        13.2,
        0.5,
        0,
        0.2,
        2.1,
        28,
      ),
      _createFood(
        'kashmiri_dum_aloo',
        'दम आलू',
        'Dum Aloo',
        'Kashmir',
        168,
        3.2,
        15.8,
        10.2,
        2.4,
        0,
        0.1,
        1.8,
        18,
      ),
      _createFood(
        'kashmiri_haaq',
        'हाक',
        'Haak (Collard Greens)',
        'Kashmir',
        42,
        3.5,
        5.8,
        0.8,
        2.2,
        0,
        0.1,
        1.2,
        145,
      ),
      _createFood(
        'kashmiri_kahwa',
        'कहवा',
        'Kahwa',
        'Kashmir',
        45,
        0.5,
        8.2,
        0.8,
        0,
        0,
        0,
        0.2,
        5,
      ),

      // Delhi/UP
      _createFood(
        'delhi_chole_kulche',
        'छोले कुल्चे',
        'Chole Kulche',
        'Delhi',
        285,
        10.2,
        48.5,
        6.8,
        3.8,
        0,
        0.3,
        3.8,
        52,
      ),
      _createFood(
        'up_dal_tadka',
        'दाल तड़का',
        'Dal Tadka',
        'Uttar Pradesh',
        128,
        6.8,
        12.2,
        5.4,
        2.8,
        0,
        0.1,
        1.9,
        32,
      ),
      _createFood(
        'up_puri_sabzi',
        'पूरी सब्जी',
        'Puri Sabzi',
        'Uttar Pradesh',
        245,
        5.2,
        38.5,
        9.8,
        2.1,
        0,
        0.2,
        2.2,
        28,
      ),
      _createFood(
        'up_galouti_kebab',
        'गलौती कबाब',
        'Galouti Kebab',
        'Uttar Pradesh',
        285,
        18.5,
        8.2,
        21.2,
        0.8,
        0,
        2.1,
        3.5,
        45,
      ),
      _createFood(
        'delhi_butter_chicken',
        'बटर चिकन',
        'Butter Chicken',
        'Delhi',
        268,
        16.5,
        5.8,
        21.2,
        1.2,
        0,
        0.5,
        1.8,
        85,
      ),

      // ============ SOUTH INDIAN ============
      // Tamil
      _createFood(
        'tamil_idli',
        'இட்லி',
        'Idli',
        'Tamil Nadu',
        121,
        4.5,
        25.2,
        0.4,
        1.2,
        0,
        0,
        0.8,
        14,
      ),
      _createFood(
        'tamil_sambar',
        'சாம்பார்',
        'Sambar',
        'Tamil Nadu',
        86,
        3.2,
        12.5,
        2.8,
        1.5,
        0,
        0,
        1.2,
        28,
      ),
      _createFood(
        'tamil_dosa',
        'தோசா',
        'Dosa',
        'Tamil Nadu',
        168,
        3.8,
        30.5,
        3.2,
        1.4,
        0,
        0,
        0.9,
        18,
      ),
      _createFood(
        'tamil_rasam',
        'ரசம்',
        'Rasam',
        'Tamil Nadu',
        42,
        1.5,
        8.2,
        0.8,
        0.5,
        0,
        0,
        0.4,
        12,
      ),
      _createFood(
        'tamil_pongal',
        'பொங்கல்',
        'Pongal',
        'Tamil Nadu',
        185,
        5.8,
        32.5,
        4.2,
        1.8,
        0,
        0.1,
        1.2,
        22,
      ),
      _createFood(
        'tamil_filter_coffee',
        'பில்டர் காபி',
        'Filter Coffee',
        'Tamil Nadu',
        52,
        1.2,
        8.5,
        1.8,
        0,
        0,
        0,
        0.4,
        110,
      ),
      _createFood(
        'tamil_vada',
        'வடை',
        'Vada',
        'Tamil Nadu',
        228,
        5.2,
        28.5,
        10.5,
        1.2,
        0,
        0.1,
        1.5,
        18,
      ),

      // Kerala
      _createFood(
        'kerala_sadhya',
        'സദ്യ',
        'Sadhya (Thali)',
        'Kerala',
        320,
        8.5,
        52.2,
        9.2,
        4.5,
        0,
        0.1,
        2.8,
        45,
      ),
      _createFood(
        'kerala_appam',
        'അപ്പം',
        'Appam',
        'Kerala',
        175,
        3.8,
        35.2,
        1.5,
        1.2,
        0,
        0,
        0.5,
        8,
      ),
      _createFood(
        'kerala_puttu',
        'പുട്ട്',
        'Puttu',
        'Kerala',
        158,
        4.2,
        32.5,
        1.8,
        2.2,
        0,
        0,
        0.8,
        12,
      ),
      _createFood(
        'kerala_fish_curry',
        'മത്സ്യ കറി',
        'Fish Curry',
        'Kerala',
        145,
        12.5,
        6.2,
        8.5,
        0.5,
        0,
        1.2,
        0.8,
        85,
      ),
      _createFood(
        'kerala_banana_fritters',
        'പഴത്തിന്റെ വറുത്തത്',
        'Banana Fritters (Pazham Pori)',
        'Kerala',
        198,
        2.2,
        28.5,
        8.8,
        2.1,
        0,
        0,
        0.4,
        8,
      ),

      // Karnataka
      _createFood(
        'karnataka_bisi_bele_bath',
        'ಬಿಸಿ ಬೇಳೆ ಬಾತ್',
        'Bisi Bele Bath',
        'Karnataka',
        185,
        5.2,
        32.5,
        4.8,
        2.8,
        0,
        0.1,
        1.5,
        32,
      ),
      _createFood(
        'karnataka_masala_dosa',
        'ಮಸಾಲ ದೋಸಾ',
        'Masala Dosa',
        'Karnataka',
        195,
        4.2,
        32.5,
        5.8,
        1.8,
        0,
        0.1,
        1.1,
        24,
      ),
      _createFood(
        'karnataka_ragi_mudde',
        'ರಾಗಿ ಮುದ್ದೆ',
        'Ragi Mudde',
        'Karnataka',
        118,
        3.2,
        25.2,
        0.8,
        2.5,
        0,
        0,
        0.5,
        45,
      ),
      _createFood(
        'karnataka_filter_coffee',
        'ಫಿಲ್ಟರ್ ಕಾಫಿ',
        'Filter Coffee',
        'Karnataka',
        48,
        1.0,
        8.2,
        1.5,
        0,
        0,
        0.4,
        38,
        0,
      ),

      // Telugu/Andhra
      _createFood(
        'telugu_pulihora',
        'తెలుగు పులిహోర',
        'Pulihora (Tamarind Rice)',
        'Telangana',
        195,
        3.5,
        38.2,
        3.8,
        1.2,
        0,
        0.1,
        1.2,
        18,
      ),
      _createFood(
        'telugu_dal',
        'తెలుగు వెల్',
        'Telugu Dal',
        'Telangana',
        115,
        5.8,
        14.2,
        4.2,
        2.2,
        0,
        0.1,
        1.4,
        28,
      ),
      _createFood(
        'andhra_chicken_curry',
        'ఆంధ్ర కురుమ',
        'Andhra Chicken Curry',
        'Andhra Pradesh',
        215,
        16.5,
        5.5,
        15.2,
        0.8,
        0,
        0.8,
        1.5,
        45,
      ),
      _createFood(
        'telugu_gongura_pachadi',
        'గుంగురా పచ్చడి',
        'Gongura Pachadi',
        'Telangana',
        45,
        1.2,
        6.5,
        1.8,
        1.5,
        0,
        0,
        0.8,
        85,
      ),

      // ============ EAST INDIAN ============
      // Bengali
      _createFood(
        'bengali_rice',
        'ভাত',
        'Bengali Rice',
        'West Bengal',
        130,
        2.5,
        28.5,
        0.3,
        0.5,
        0,
        0,
        0.3,
        8,
      ),
      _createFood(
        'bengali_fish_curry',
        'মাছের ঝোল',
        'Fish Curry (Machher Jhol)',
        'West Bengal',
        145,
        14.5,
        5.8,
        8.2,
        0.5,
        0,
        0.8,
        0.6,
        72,
      ),
      _createFood(
        'bengali_shabds',
        'শবদ',
        'Shabds (Fried Fish)',
        'West Bengal',
        185,
        12.8,
        8.2,
        12.5,
        0.8,
        0,
        0.5,
        0.4,
        55,
      ),
      _createFood(
        'bengali_rasgulla',
        'রসগোল্লা',
        'Rasgulla',
        'West Bengal',
        186,
        4.2,
        42.5,
        0.4,
        0.2,
        0,
        0,
        0.1,
        35,
      ),
      _createFood(
        'bengali_sandesh',
        'সন্দেশ',
        'Sandesh',
        'West Bengal',
        175,
        5.8,
        38.2,
        0.5,
        0.1,
        0,
        0,
        0.1,
        48,
      ),
      _createFood(
        'bengali_luchi',
        'লুচি',
        'Luchi',
        'West Bengal',
        248,
        4.2,
        48.5,
        5.2,
        0.8,
        0,
        0.1,
        0.2,
        12,
      ),
      _createFood(
        'bengali_misti_doi',
        'মিষ্টি দই',
        'Misti Doi',
        'West Bengal',
        118,
        3.5,
        22.5,
        2.2,
        0.1,
        0,
        0,
        0.1,
        85,
      ),

      // Odia
      _createFood(
        'odisha_pakhala',
        'ପଖଳା',
        'Pakhala Bhata',
        'Odisha',
        95,
        1.8,
        22.5,
        0.2,
        0.4,
        0,
        0,
        0.2,
        8,
      ),
      _createFood(
        'odisha_rasabali',
        'ରସାବଳୀ',
        'Rasabali',
        'Odisha',
        195,
        4.2,
        38.5,
        3.5,
        0.5,
        0,
        0,
        0.2,
        42,
      ),
      _createFood(
        'odisha_pithas',
        'ପିଠା',
        'Pithas',
        'Odisha',
        165,
        3.2,
        32.5,
        2.8,
        1.2,
        0,
        0,
        0.5,
        18,
      ),

      // Assamese
      _createFood(
        'assam_khar',
        'খাৰ',
        'Khar',
        'Assam',
        78,
        2.5,
        12.5,
        2.2,
        1.8,
        0,
        0,
        0.5,
        28,
      ),
      _createFood(
        'assam_masor_tenga',
        'মাছৰ টেংগা',
        'Masor Tenga (Sour Fish Curry)',
        'Assam',
        125,
        12.5,
        4.2,
        7.2,
        0.4,
        0,
        0.6,
        0.5,
        65,
      ),
      _createFood(
        'assam_xâu',
        'শৌ',
        'Xâu (Bamboo Shoot Curry)',
        'Assam',
        95,
        8.2,
        8.5,
        5.2,
        1.2,
        0,
        0.2,
        0.8,
        35,
      ),

      // ============ WEST INDIAN ============
      // Gujarati
      _createFood(
        'gujarati_dhokla',
        'ઢોકળા',
        'Dhokla',
        'Gujarat',
        145,
        4.2,
        28.5,
        2.2,
        1.5,
        0,
        0,
        0.8,
        22,
      ),
      _createFood(
        'gujarati_thepla',
        'થેપ્લા',
        'Thepla',
        'Gujarat',
        198,
        5.8,
        32.5,
        5.2,
        2.2,
        0,
        0.1,
        1.2,
        28,
      ),
      _createFood(
        'gujarati_khandvi',
        'ખાંડવી',
        'Khandvi',
        'Gujarat',
        175,
        3.5,
        28.2,
        5.8,
        0.8,
        0,
        0.1,
        0.4,
        18,
      ),
      _createFood(
        'gujarati_dal_dhokhi',
        'દાલ ધોખી',
        'Dal Dhokhi',
        'Gujarat',
        165,
        6.2,
        28.5,
        3.5,
        2.5,
        0,
        0.1,
        1.2,
        32,
      ),
      _createFood(
        'gujarati_fafda_jalebi',
        'ફાફડા જલેબી',
        'Fafda Jalebi',
        'Gujarat',
        285,
        3.2,
        48.5,
        8.8,
        0.5,
        0,
        0.1,
        0.3,
        15,
      ),
      _createFood(
        'gujarati_rotlo',
        'રોટલો',
        'Rotlo (Bajra Roti)',
        'Gujarat',
        218,
        5.2,
        45.2,
        1.8,
        3.2,
        0,
        0.1,
        1.8,
        28,
      ),

      // Maharashtrian
      _createFood(
        'maharashtrian_puran_poli',
        'पुरण पोली',
        'Puran Poli',
        'Maharashtra',
        245,
        6.2,
        48.5,
        4.8,
        1.5,
        0,
        0.1,
        0.8,
        35,
      ),
      _createFood(
        'maharashtrian_misal_pav',
        'मिसल पाव',
        'Misal Pav',
        'Maharashtra',
        225,
        8.5,
        32.5,
        8.2,
        2.8,
        0,
        0.2,
        1.5,
        52,
      ),
      _createFood(
        'maharashtrian_vada_pav',
        'वडा पाव',
        'Vada Pav',
        'Maharashtra',
        195,
        4.8,
        28.5,
        7.8,
        1.5,
        0,
        0.1,
        0.8,
        22,
      ),
      _createFood(
        'maharashtrian_pithla_bhakri',
        'पिठला भाकरी',
        'Pithla Bhakri',
        'Maharashtra',
        185,
        5.2,
        32.5,
        4.2,
        2.5,
        0,
        0.1,
        1.2,
        35,
      ),
      _createFood(
        'maharashtrian_kothimbir_vadi',
        'कोथिंबीर वडी',
        'Kothimbir Vadi',
        'Maharashtra',
        145,
        4.2,
        18.5,
        6.5,
        1.8,
        0,
        0.1,
        0.8,
        42,
      ),

      // Rajasthani
      _createFood(
        'rajasthani_dal_baati_churma',
        'दाल बाटी चूरमा',
        'Dal Baati Churma',
        'Rajasthan',
        285,
        8.5,
        48.2,
        7.2,
        3.5,
        0,
        0.2,
        2.2,
        38,
      ),
      _createFood(
        'rajasthani_ghevar',
        'घेवડાર',
        'Ghevar',
        'Rajasthan',
        315,
        4.8,
        58.5,
        8.2,
        0.8,
        0,
        0.1,
        0.5,
        28,
      ),
      _createFood(
        'rajasthani_laal_maas',
        'लाल मांस',
        'Laal Maas',
        'Rajasthan',
        245,
        18.5,
        5.2,
        18.2,
        0.5,
        0,
        1.2,
        2.1,
        35,
      ),
      _createFood(
        'rajasthani_ker_sangri',
        'केर सांગરી',
        'Ker Sangri',
        'Rajasthan',
        125,
        3.2,
        22.5,
        3.8,
        2.2,
        0,
        0.1,
        1.5,
        45,
      ),
      _createFood(
        'rajasthani_bajra_roti',
        'બાજરી રોટી',
        'Bajra Roti',
        'Rajasthan',
        198,
        4.8,
        42.2,
        1.5,
        3.2,
        0,
        0.1,
        1.5,
        24,
      ),

      // ============ NORTHEAST INDIAN ============
      // Nagaland
      _createFood(
        'naga_smoked_pork',
        'Naga Smoked Pork',
        'Naga Smoked Pork',
        'Nagaland',
        285,
        22.5,
        2.8,
        21.2,
        0.2,
        0,
        0.8,
        1.2,
        18,
      ),
      _createFood(
        'naga_axone',
        'Axone (Fermented Soybean)',
        'Axone',
        'Nagaland',
        145,
        12.5,
        8.2,
        8.5,
        2.5,
        0,
        0,
        2.8,
        85,
      ),
      _createFood(
        'naga_rice_beer',
        'Rice Beer',
        'Rice Beer',
        'Nagaland',
        85,
        0.5,
        12.5,
        0.2,
        0,
        0,
        0,
        0.2,
        8,
      ),

      // Meghalaya
      _createFood(
        'meghalaya_jadoh',
        'Jadoh',
        'Jadoh (Pork Rice)',
        'Meghalaya',
        225,
        12.2,
        32.5,
        7.8,
        1.2,
        0,
        0.5,
        1.5,
        45,
      ),
      _createFood(
        'meghalaya_ki_kong',
        'Ki Kong',
        'Ki Kong (Bamboo Shoot Curry)',
        'Meghalaya',
        95,
        6.5,
        12.2,
        4.2,
        2.2,
        0,
        0.1,
        0.8,
        52,
      ),

      // Sikkim
      _createFood(
        'sikkim_momos',
        'मोमोस',
        'Momos',
        'Sikkim',
        185,
        6.2,
        28.5,
        5.8,
        1.5,
        0,
        0.1,
        0.6,
        22,
      ),
      _createFood(
        'sikkim_thukpa',
        'थुकपा',
        'Thukpa',
        'Sikkim',
        165,
        8.5,
        22.5,
        5.2,
        2.2,
        0,
        0.1,
        1.2,
        35,
      ),
      _createFood(
        'sikkim_sel_roti',
        'सेल रोटी',
        'Sel Roti',
        'Sikkim',
        225,
        4.2,
        42.5,
        5.2,
        1.2,
        0,
        0.1,
        0.5,
        28,
      ),

      // ============ CENTRAL INDIAN ============
      // Madhya Pradesh
      _createFood(
        'mp_dal_bafla',
        'दाल बाफला',
        'Dal Bafla',
        'Madhya Pradesh',
        245,
        8.2,
        42.5,
        6.2,
        3.2,
        0,
        0.1,
        1.5,
        35,
      ),
      _createFood(
        'mp_poha',
        'पोहा',
        'Poha',
        'Madhya Pradesh',
        165,
        4.2,
        28.5,
        3.8,
        1.8,
        0,
        0.1,
        0.8,
        18,
      ),
      _createFood(
        'mp_garamm_garam_sabzi',
        'गरम गरम सब्जी',
        'Garamm Garam Sabzi',
        'Madhya Pradesh',
        95,
        2.5,
        12.5,
        4.2,
        2.5,
        0,
        0.1,
        0.8,
        28,
      ),

      // Chhattisgarh
      _createFood(
        'chhattisgarh_bhor_coke',
        'भोर कोक',
        'Bhor Coke',
        'Chhattisgarh',
        165,
        3.8,
        32.5,
        2.2,
        2.2,
        0,
        0,
        0.8,
        22,
      ),
      _createFood(
        'chhattisgarh_achhotra',
        'अच्छोत्रा',
        'Achhotra',
        'Chhattisgarh',
        145,
        8.5,
        12.2,
        7.5,
        2.5,
        0,
        0.2,
        1.2,
        85,
      ),

      // ============ COMMON INDIAN ITEMS ============
      // Breads
      _createFood(
        'tandoori_roti',
        'तंदूरी रोटी',
        'Tandoori Roti',
        'Pan-India',
        185,
        4.2,
        38.5,
        1.5,
        1.8,
        0,
        0.1,
        0.5,
        12,
      ),
      _createFood(
        'naan',
        'नान',
        'Naan',
        'Pan-India',
        215,
        6.2,
        42.5,
        2.8,
        1.5,
        0,
        0.1,
        0.6,
        18,
      ),
      _createFood(
        'paratha',
        'पराठा',
        'Paratha',
        'Pan-India',
        245,
        5.8,
        45.2,
        6.2,
        2.2,
        0,
        0.1,
        0.8,
        22,
      ),
      _createFood(
        'rumali_roti',
        'रुमाली रोटी',
        'Rumali Roti',
        'Pan-India',
        145,
        3.2,
        32.5,
        0.8,
        1.2,
        0,
        0,
        0.3,
        8,
      ),

      // Rice dishes
      _createFood(
        'biryani',
        'बिरयानी',
        'Biryani',
        'Pan-India',
        225,
        8.5,
        35.2,
        6.8,
        1.8,
        0,
        0.2,
        1.2,
        32,
      ),
      _createFood(
        'jeera_rice',
        'जीरा चावल',
        'Jeera Rice',
        'Pan-India',
        185,
        3.8,
        35.5,
        3.2,
        1.2,
        0,
        0.1,
        0.5,
        18,
      ),
      _createFood(
        'veg_pulao',
        'वेज पुलाव',
        'Veg Pulao',
        'Pan-India',
        165,
        3.5,
        32.5,
        2.8,
        1.5,
        0,
        0.1,
        0.6,
        22,
      ),

      // Snacks
      _createFood(
        'samosa',
        'समोसा',
        'Samosa',
        'Pan-India',
        225,
        5.2,
        28.5,
        11.2,
        1.8,
        0,
        0.1,
        0.6,
        18,
      ),
      _createFood(
        'pakora',
        'पकोड़ा',
        'Pakora',
        'Pan-India',
        198,
        4.2,
        22.5,
        10.8,
        1.5,
        0,
        0.1,
        0.5,
        22,
      ),
      _createFood(
        'bhajiya',
        'भाजिया',
        'Bhajiya',
        'Pan-India',
        215,
        3.8,
        25.2,
        11.5,
        1.8,
        0,
        0.1,
        0.4,
        15,
      ),
      _createFood(
        'chai',
        'चाय',
        'Chai (Tea)',
        'Pan-India',
        45,
        1.2,
        7.2,
        1.2,
        0.2,
        0,
        0,
        0.1,
        42,
      ),

      // Sweets
      _createFood(
        'gulab_jamun',
        'गुलाब जामुन',
        'Gulab Jamun',
        'Pan-India',
        245,
        4.2,
        48.5,
        5.2,
        0.5,
        0,
        0.1,
        0.3,
        28,
      ),
      _createFood(
        'jalebi',
        'जलेबी',
        'Jalebi',
        'Pan-India',
        285,
        3.5,
        52.2,
        7.8,
        0.4,
        0,
        0.1,
        0.2,
        18,
      ),
      _createFood(
        'ladoo',
        'लड्डू',
        'Ladoo',
        'Pan-India',
        225,
        3.8,
        42.5,
        5.5,
        0.8,
        0,
        0.1,
        0.4,
        22,
      ),
      _createFood(
        'halwa',
        'हलवा',
        'Halwa',
        'Pan-India',
        195,
        3.2,
        35.2,
        5.2,
        1.2,
        0,
        0.1,
        0.5,
        28,
      ),
      _createFood(
        'kheer',
        'खीर',
        'Kheer',
        'Pan-India',
        145,
        4.2,
        25.5,
        3.2,
        0.5,
        0,
        0.1,
        0.3,
        85,
      ),
      _createFood(
        'rabdi',
        'रबड़ी',
        'Rabdi',
        'Rajasthan',
        165,
        5.5,
        22.5,
        5.8,
        0.4,
        0,
        0.1,
        0.2,
        95,
      ),

      // Lentils/Dals
      _createFood(
        'dal_fry',
        'दाल फ्राई',
        'Dal Fry',
        'Pan-India',
        115,
        6.2,
        12.5,
        4.8,
        2.2,
        0,
        0.1,
        1.4,
        28,
      ),
      _createFood(
        'dal_tadka',
        'दाल तड़का',
        'Dal Tadka',
        'Pan-India',
        125,
        6.5,
        14.2,
        5.2,
        2.5,
        0,
        0.1,
        1.5,
        32,
      ),
      _createFood(
        'rajma',
        'राजमा',
        'Rajma',
        'North India',
        145,
        8.5,
        26.2,
        1.8,
        6.5,
        0,
        0,
        2.2,
        38,
      ),
      _createFood(
        'chole',
        'छोले',
        'Chole (Chickpeas)',
        'North India',
        165,
        8.2,
        27.5,
        3.2,
        6.2,
        0,
        0.1,
        2.5,
        48,
      ),

      // Vegetables
      _createFood(
        'aloo_gobi',
        'आलू गोभी',
        'Aloo Gobi',
        'Pan-India',
        85,
        2.2,
        12.5,
        3.2,
        2.5,
        0,
        0.1,
        0.8,
        32,
      ),
      _createFood(
        'palak_paneer',
        'पालक पनीर',
        'Palak Paneer',
        'North India',
        165,
        10.5,
        6.2,
        11.8,
        1.8,
        0,
        0.3,
        1.5,
        195,
      ),
      _createFood(
        'bhindi_masala',
        'भिंडी मसाला',
        'Bhindi Masala',
        'Pan-India',
        95,
        2.8,
        10.5,
        4.8,
        2.8,
        0,
        0.1,
        1.2,
        42,
      ),
      _createFood(
        'baingan_bharta',
        'बैंगन भर्ता',
        'Baingan Bharta',
        'Pan-India',
        78,
        2.2,
        8.5,
        4.2,
        2.2,
        0,
        0.1,
        0.8,
        25,
      ),
      _createFood(
        'mix_veg',
        'मिक्स वेज',
        'Mix Vegetable',
        'Pan-India',
        82,
        2.5,
        10.2,
        3.5,
        2.5,
        0,
        0.1,
        0.7,
        28,
      ),

      // Meat
      _createFood(
        'chicken_curry',
        'चिकन करी',
        'Chicken Curry',
        'Pan-India',
        185,
        15.2,
        5.5,
        12.5,
        0.8,
        0,
        0.3,
        1.2,
        55,
      ),
      _createFood(
        'mutton_curry',
        'मटन करी',
        'Mutton Curry',
        'Pan-India',
        215,
        16.5,
        5.2,
        16.2,
        0.8,
        0,
        0.8,
        1.5,
        45,
      ),
      _createFood(
        'fish_fry',
        'फिश फ्राई',
        'Fish Fry',
        'Pan-India',
        165,
        14.5,
        4.2,
        10.8,
        0.5,
        0,
        0.3,
        0.5,
        65,
      ),
      _createFood(
        'egg_curry',
        'अंडा करी',
        'Egg Curry',
        'Pan-India',
        145,
        9.5,
        6.2,
        9.8,
        1.2,
        0,
        0.2,
        0.8,
        52,
      ),
    ];
  }

  /// Create a food item map
  static Map<String, dynamic> _createFood(
    String id,
    String nameLocal,
    String name,
    String region,
    double calories,
    double protein,
    double carbs,
    double fat,
    double fiber,
    double vitaminD,
    double vitaminB12,
    double iron,
    double calcium,
  ) {
    // Generate serving sizes based on region
    final servingSizes = _getServingSizes(region, name);

    return {
      'id': id,
      'name': name,
      'name_local': nameLocal,
      'region': region,
      'barcode': null,
      'calories_per_100g': calories,
      'protein_per_100g': protein,
      'carbs_per_100g': carbs,
      'fat_per_100g': fat,
      'fiber_per_100g': fiber,
      'vitamin_d_per_100g': vitaminD,
      'vitamin_b12_per_100g': vitaminB12,
      'iron_per_100g': iron,
      'calcium_per_100g': calcium,
      'is_indian': true,
      'serving_sizes': jsonEncode(servingSizes),
      'source': 'fitkarma_seed',
    };
  }

  /// Get region-specific serving sizes
  static List<Map<String, dynamic>> _getServingSizes(
    String region,
    String foodName,
  ) {
    // Common serving sizes for Indian foods
    final List<Map<String, dynamic>> commonSizes = [
      {'name': 'katori', 'grams': 150},
      {'name': 'plate', 'grams': 300},
      {'name': 'piece', 'grams': 50},
      {'name': 'cup', 'grams': 200},
    ];

    // Region-specific modifications
    switch (region.toLowerCase()) {
      case 'punjab':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'roti', 'grams': 35},
          {'name': 'plate', 'grams': 350},
        ];
      case 'tamil nadu':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'idli', 'grams': 35},
          {'name': 'dosa', 'grams': 80},
        ];
      case 'kerala':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'appam', 'grams': 60},
          {'name': 'banana_leaf', 'grams': 400},
        ];
      case 'west bengal':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'bhon', 'grams': 150},
          {'name': 'piece', 'grams': 75},
        ];
      case 'gujarat':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'thepla', 'grams': 45},
          {'name': 'rotlo', 'grams': 60},
        ];
      case 'maharashtra':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'pav', 'grams': 50},
          {'name': 'bhakri', 'grams': 80},
        ];
      case 'rajasthan':
        return [
          {'name': 'katori', 'grams': 150},
          {'name': 'baati', 'grams': 50},
          {'name': 'churma', 'grams': 30},
        ];
      default:
        return commonSizes;
    }
  }

  /// Get unique regions
  static List<String> getUniqueRegions() {
    final foods = getAllFoods();
    final regions = foods.map((f) => f['region'] as String).toSet().toList();
    regions.sort();
    return regions;
  }
}
